schema_version: 1

package:
  name: epoc
  version: 2024.7.25

source:
  path: ..

build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - rich
    - redis-py

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      - echo "Hello world"
      - pytest ./tests

    # additional requirements at test time
    requirements:
      run:
        - pytest

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - tests/
        # - test.py
        # - *.sh
      # recipe:
      #   - more_tests/*.py

  # This test section tries to import the Python modules and errors if it can't
  - python:
      imports:
        - epoc

about:
  license: MIT
  summary: Configuration of experiments in the EPOC project
  homepage: https://github.com/epoc-ed/epoc-utils

